#!/usr/bin/env python3
"""Generate paper-style personalized skills directly from historical user messages."""

from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path
from typing import Any

import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SELECTION = ROOT / "outputs/longitudinal_pilot/four_user_extraction/selected_sessions.json"
DEFAULT_DATA = ROOT / "data/swechat_data"
DEFAULT_OUTPUT = ROOT / "outputs/longitudinal_pilot/personalized_skills"
USERS = ("Soph", "khaong", "Nagi-ovo")
FRONT_MATTER = """---
name: personalized-developer-skill
description: Task-independent behavioral preferences inferred from prior coding-agent interactions.
---"""

STAGE1_INSTRUCTIONS = f"""You are constructing a task-independent bootstrap coding-agent skill profile for a specific developer.
You are given user-authored messages from multiple historical coding-agent sessions.
Identify recurring interaction patterns that could help a coding agent work better with this developer on a future, unseen coding task.
Focus on:
Communication style
Work style
Follow-up and correction behavior
Validation preferences, only when explicitly recurring
Commit preferences, only when explicitly recurring
Also include a small number of short, sanitized representative interaction-style examples when useful.
Important:
Capture HOW the developer prefers to work, not WHAT they asked for in a particular task.
Do not assume future tasks use the same repository, language, framework, files, tools, or domain.
Do not generalize isolated task requirements into preferences.
Prefer recurring patterns across multiple sessions.
Do not include generic software-engineering advice unless the user's interactions provide evidence that they specifically prefer it.
Keep the skill compact.
The output MUST begin with exactly this YAML front matter:

{FRONT_MATTER}

Then produce the bootstrap SKILL.md with this structure:
Scope
State that the skill adapts agent behavior only. The active user request, current repository, and execution environment remain authoritative.
Communication
Work Style
Follow-Up Handling
Validation
Commits
Training-Split Examples
Omit unsupported content rather than inventing preferences.
Output only SKILL.md."""

STAGE2_TEMPLATE = """You are refining a coding-agent skill profile for a specific SWE-chat user.
Your job is to make the draft skill slightly more accurate and useful while keeping it task-independent, compact, and safe for unseen test sessions that may involve different repositories or task types.
Draft skill (generated by pattern analysis)
{bootstrap_skill}
User's training sessions ({n_sessions} sessions, {n_turns} user turns)
{session_block}
Task
Produce a single improved SKILL.md.
Rules:
Preserve the existing YAML front-matter format.
Preserve the Scope section's safety intent: the skill adapts behavior only, and the active user request, local repository, and replay worktree remain authoritative.
Treat the session block as the ground truth. The draft skill is a heuristic starting point — accept, revise, or delete each rule based on whether it is confirmed by recurring evidence in the session block.
Remove any bootstrap rule that is not supported by at least two independent user turns across different sessions.
Add rules for clear patterns visible in the session block that the draft skill missed.
Focus refinement primarily on Communication, Work Style, and Follow-Up Handling.
Only adjust Validation or Commits when the training sessions show a recurring user preference, and keep those rules conditional on the active request.
Stay task-independent: capture how the user works, not what they asked for in training.
Capture the user's style preferences: communication tone, directness, edit scope, claim precision, follow-up handling, commit hygiene when requested, and validation style when relevant.
Generalize only stable behavior patterns supported by multiple user turns or clearly recurring interaction style.
Do NOT infer that future test sessions will use the same repo, files, UI surfaces, tools, issues, frameworks, languages, domains, or task type as training sessions.
Do NOT mention specific repos, filenames, paths, issue IDs, commit hashes, exact labels, exact user examples, URLs, logs, metrics, or task content from above.
Do NOT add product requirements, feature requirements, validation requirements, or delivery requirements unless they are explicitly conditional on the active request.
Do NOT prescribe specific CLI commands, tool names, or environment-dependent steps.
Do NOT generate guidance that causes the agent to stop or report failure merely because a tool, file, repo layout, or CLI is unavailable.
Do NOT generate guidance that could cause the agent to implement less than what the user explicitly requested.
Do not expand the skill with environment setup instructions, project-specific workflows, or task-domain playbooks.
Avoid long or redundant skills. Keep only guidance that would help on an unseen task for this user.
Training-Split Examples, if included, must be short and sanitized. They must illustrate interaction style only, not preserve task details.
Output only the final SKILL.md content, no commentary."""


def load_env() -> None:
    for path in (ROOT / ".env", ROOT / "third_party/.env", ROOT / "third_party/SWE-Together/.env"):
        if not path.exists():
            continue
        for raw in path.read_text().splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def serialize_sessions(frame: pd.DataFrame, session_ids: list[str]) -> tuple[str, int]:
    blocks: list[str] = []
    total_turns = 0
    for session_id in session_ids:
        rows = frame[
            (frame["session_id"].astype(str) == session_id)
            & (frame["role"] == "user")
            & frame["is_conversational"].fillna(False)
        ].sort_values("turn_number")
        lines = [f"=== Session: {session_id} ==="]
        for ordinal, row in enumerate(rows.itertuples(index=False), start=1):
            lines.extend([f"[User Turn {ordinal}]", str(row.content or "").strip()])
            total_turns += 1
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks), total_turns


def strip_fence(text: str) -> str:
    value = text.strip()
    if value.startswith("```markdown") and value.endswith("```"):
        value = value[len("```markdown"): -3].strip()
    elif value.startswith("```") and value.endswith("```"):
        value = value[3:-3].strip()
    return value + "\n"


def enforce_fixed_front_matter(text: str) -> str:
    """Replace only model-authored YAML metadata; leave the learned body intact."""
    value = strip_fence(text).lstrip()
    if value.startswith("---\n"):
        closing = value.find("\n---", 4)
        if closing != -1:
            value = value[closing + len("\n---"):].lstrip("\n")
    return FRONT_MATTER + "\n\n" + value


def validate_skill(text: str) -> None:
    if not text.startswith(FRONT_MATTER + "\n"):
        raise ValueError("model output did not preserve the exact fixed YAML front matter")
    for heading in ("Scope", "Communication", "Work Style", "Follow-Up Handling"):
        if heading not in text:
            raise ValueError(f"model output is missing required section: {heading}")


def api_call(client: Any, *, model: str, prompt: str, max_output_tokens: int,
             stage: str, user: str) -> tuple[str, dict[str, Any]]:
    last_error: Exception | None = None
    for attempt in range(4):
        try:
            params = {
                "model": model,
                "input": prompt,
                "reasoning": {"effort": "low"},
                "max_output_tokens": max_output_tokens,
                "store": False,
            }
            response = client.responses.create(**params)
            usage = getattr(response, "usage", None)
            metadata = {
                "response_id": getattr(response, "id", None),
                "usage": usage.model_dump() if hasattr(usage, "model_dump") else None,
                "parameters": {
                    "model": model,
                    "reasoning": {"effort": "low"},
                    "max_output_tokens": max_output_tokens,
                    "store": False,
                    "temperature": "not supplied; unsupported for this reasoning-model configuration",
                },
            }
            return strip_fence(response.output_text), metadata
        except Exception as error:
            last_error = error
            print(f"[{user}] {stage} attempt {attempt + 1}/4 failed: {error}", flush=True)
            if attempt < 3:
                time.sleep(2 ** attempt)
    raise RuntimeError(f"{stage} failed for {user}") from last_error


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--selection", type=Path, default=DEFAULT_SELECTION)
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--model", default="gpt-5.4-mini")
    args = parser.parse_args()
    load_env()
    if not os.getenv("OPENAI_API_KEY"):
        raise SystemExit("OPENAI_API_KEY is required")

    selection = {
        row["user"]: row for row in json.loads(args.selection.read_text())
        if row["user"] in USERS
    }
    session_ids = [
        str(session["session_id"])
        for user in USERS for session in selection[user]["selected"]
    ]
    frame = pd.read_parquet(
        args.data_dir / "conversations.parquet",
        filters=[("session_id", "in", session_ids), ("role", "=", "user")],
        columns=["session_id", "turn_number", "role", "is_conversational", "content"],
    )
    from openai import OpenAI
    client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
    args.out_dir.mkdir(parents=True, exist_ok=True)

    for user in USERS:
        user_dir = args.out_dir / user
        user_dir.mkdir(parents=True, exist_ok=True)
        ids = [str(session["session_id"]) for session in selection[user]["selected"]]
        session_block, n_turns = serialize_sessions(frame, ids)
        stage1_prompt = STAGE1_INSTRUCTIONS + "\n\nUser-authored historical sessions\n" + session_block
        print(f"[{user}] Stage 1: {len(ids)} sessions, {n_turns} user turns", flush=True)
        bootstrap, stage1_meta = api_call(
            client, model=args.model, prompt=stage1_prompt, max_output_tokens=5000,
            stage="Stage 1", user=user,
        )
        (user_dir / "stage1_prompt.txt").write_text(stage1_prompt)
        (user_dir / "stage1_raw_response.md").write_text(bootstrap)
        bootstrap = enforce_fixed_front_matter(bootstrap)
        validate_skill(bootstrap)
        (user_dir / "bootstrap_skill.md").write_text(bootstrap)
        (user_dir / "stage1_metadata.json").write_text(json.dumps(stage1_meta, indent=2) + "\n")
        print(f"[{user}] Stage 1 complete; Stage 2 refinement", flush=True)

        stage2_prompt = STAGE2_TEMPLATE.format(
            bootstrap_skill=bootstrap.rstrip(), n_sessions=len(ids),
            n_turns=n_turns, session_block=session_block,
        )
        final_skill, stage2_meta = api_call(
            client, model=args.model, prompt=stage2_prompt, max_output_tokens=5000,
            stage="Stage 2", user=user,
        )
        (user_dir / "stage2_raw_response.md").write_text(final_skill)
        final_skill = enforce_fixed_front_matter(final_skill)
        validate_skill(final_skill)
        (user_dir / "stage2_prompt.txt").write_text(stage2_prompt)
        (user_dir / "SKILL.md").write_text(final_skill)
        (user_dir / "stage2_metadata.json").write_text(json.dumps(stage2_meta, indent=2) + "\n")
        metadata = {
            "user": user,
            "model": args.model,
            "session_ids": ids,
            "n_sessions": len(ids),
            "n_user_turns": n_turns,
            "input_policy": "role=user and is_conversational=true; assistant messages, tools, diffs, and repository content excluded",
            "front_matter": FRONT_MATTER,
            "stage1": stage1_meta,
            "stage2": stage2_meta,
            "artifacts": {
                "stage1_prompt": "stage1_prompt.txt",
                "stage2_prompt": "stage2_prompt.txt",
                "bootstrap_output": "bootstrap_skill.md",
                "final_skill": "SKILL.md",
            },
        }
        (user_dir / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
        print(f"[{user}] complete: {user_dir / 'SKILL.md'}", flush=True)


if __name__ == "__main__":
    main()
